FROM openjdk:8-jdk-alpine
MAINTAINER cagdasalagoz@gmail.com

COPY ./build/libs/auth-service-0.0.1-SNAPSHOT.jar /usr/src/auth-service/

CMD ["java","-jar","/usr/src/auth-service/auth-service-0.0.1-SNAPSHOT.jar"]