FROM openjdk:8-jdk-alpine
MAINTAINER cagdasalagoz@gmail.com

COPY ./build/libs/email-service-0.0.1-SNAPSHOT.jar /usr/src/email-service/

CMD ["java","-jar","/usr/src/email-service/email-service-0.0.1-SNAPSHOT.jar"]